### PR TITLE
Use Dagger for dependency injection

### PR DESCRIPTION
**Pull request by tkindy**
This PR implements dependency injection using Dagger 2. I extracted all of the objects being created in `BusApplication` into modules as a first step.

### CODE REVIEW

**Comment by ronocod** [comment]
I'm not too sure on this. I like Dagger in big projects but I'd rather not use it when it's not needed. We only have 2 real components here and although I think we can manage them better (they definitely should be moved out of the Application class), I'd rather have a more simple solution here.

**Comment by tkindy** [comment]
I get that. I suppose it depends on how much you're planning on extending the app. Right now, there are only two dependencies to be injected, but even a small project can have a proliferation of objects.

If the app is already as feature-complete as you're planning on it being, it's probably not worth it. As the project owner, it's your call to make and I'll go with your decision.

**Comment by ronocod** [comment]
We'll leave it for now I think, I'm not planning to extend this in the foreseeable future. If I do extend it again I'll let you make the Dagger PR during the next Hacktoberfest event 😄

**Comment by tkindy** [comment]
Haha you're very gracious :bowing_man:

**Pull request closed without merging**
